<select class="form-control" id="state" name="state" onchange="getLocalGovernment()">
    <option value="">Select State</option> 
    <option value="Abia State">Abia</option>
    <option value="Adamawa State">Adamawa</option>
    <option value="Akwa Ibom State">Akwa Ibom</option>
    <option value="Anambra State">Anambra</option>
    <option value="Bauchi State">Bauchi</option>
    <option value="Bayelsa State">Bayelsa</option>
    <option value="Benue State">Benue</option>
    <option value="Borno State">Borno</option>
    <option value="Cross River State">Cross River</option>
    <option value="Delta State">Delta</option>
    <option value="Ebonyi State">Ebonyi</option> 
    <option value="Edo State">Edo</option>
    <option value="Ekiti State">Ekiti</option>
    <option value="Enugu State">Enugu</option>
    <option value="FCT">FCT</option>
    <option value="Gombe State">Gombe</option>
    <option value="Imo State">Imo</option>
    <option value="Jigawa State">Jigawa</option>
    <option value="Kaduna State">Kaduna</option>
    <option value="Kano State">Kano</option>
    <option value="Kastina State">Kastina</option>
    <option value="Kebbi State">Kebbi</option>
    <option value="Kogi State">Kogi</option>
    <option value="Kwara State">Kwara</option>
    <option value="Lagos State">Lagos</option>
    <option value="Nasarawa State">Nasarawa </option>
    <option value="Niger State">Niger</option>
    <option value="Ogun State">Ogun</option>
    <option value="Ondo State">Ondo</option>
    <option value="Osun State">Osun</option>
    <option value="Oyo State">Oyo</option>
    <option value="Plateau State">Plateau</option>
    <option value="Rivers State">Rivers</option>
    <option value="Sokoto State">Sokoto</option>
    <option value="Taraba State">Taraba</option>
    <option value="Yobe State">Yobe</option>
    <option value="Zamfara State">Zamfara</option>
</select>